k:
  config:
    # 引入其他配置
    include:
      - application-feign.yml
      - application-mybatis.yml
      - application-mail.yml
      - application-dubbo.yml
  server:
    port: 8080
    virtualThread: true
  mvc:
    netty:
      accessLog: false

rocketmq:
  endpoints: 127.0.0.1:28081    # 对应 rmq-proxy.json#grpcServerPort

template:
  thymeleaf:
    prefix: /template/
    suffix: .html
