k:
  config:
    # 引入其他配置
    include: application-mybatis.yml,application-mail.yml
  server:
    port: 8080
    virtualThread: true
  mvc:
    netty:
      accessLog: false

template:
  thymeleaf:
    prefix: /template/
    suffix: .html
